### ISSUE TITLE
Execute requests only on development or local NODE_ENV

### ISSUE THREAD

**Issue by jonorozcoc** [permafrost-dev/node-ray#15]
**Describe the bug**

Sending info in staging or production environments

**To Reproduce**

1. Install the library
2. Deploy it with NODE_ENV=staging or NODE_ENV=production

**Expected behavior**

Not to send requests to ray desktop app

**Environment (please complete the following information):**

 - OS: Windows 10
 - NodeJS Version 12
 - Language & Version Javascript

**Comment by patinthehat** [comment]
@jonorozcoc version 1.9.1+ no longer sends data to Ray when `NODE_ENV` is "production" or "staging".

Please reopen the issue if it doesn't.  Thank you!
