### ISSUE TITLE
Typescript typings not available for node-ray/web

### ISSUE THREAD

**Issue by tpetry** [permafrost-dev/node-ray#17]
**Describe the bug**

The typescript typings are not available when using `node-ray` in a webpack context.

**To Reproduce**

```ts
import {
  ray,
} from "node-ray/web";
```

**Error**

```
TS7016: Could not find a declaration file for module 'node-ray/web'. '/Users/tpetry/Documents/application-xyz/node_modules/node-ray/web.js' implicitly has an 'any' type.   Try `npm i --save-dev @types/node-ray` if it exists or add a new declaration (.d.ts) file containing `declare module 'node-ray/web';`
```

**Comment by patinthehat** [comment]
I've been looking into this and hope to have a solution soon.  Stay tuned.

**Comment by ffxsam** [comment]
This still doesn't work. Any workarounds, at least?

**Comment by ffxsam** [comment]
This seems to work as a workaround:

1. Edit your `tsconfig.json` to include some sort of declarations file in your project, e.g.: `include: ["src/declarations.d.ts"]`
2. Add the below code to `declarations.d.ts`:
```ts
declare module 'node-ray/web' {
  import { ray } from 'node-ray';
  export { ray };
}
```

All fixed!

**Comment by patinthehat** [comment]
@ffxsam Thank you for this! I hope to have time to get back to this soon! :+1:

**Comment by ffxsam** [comment]
Hey @patinthehat, a buddy of mine has expressed some interest in making some changes to `node-ray` so that it when it's passed objects, each object/array is collapsible. How complex an undertaking would this be?

**Comment by patinthehat** [comment]
Let's move the discussion there :+1:

**Comment by patinthehat** [comment]
@tpetry Sorry for the delay - [v1.19.6](https://github.com/permafrost-dev/node-ray/releases/tag/v1.19.6) now has typescript types for `node-ray/web`.

**Comment by rinodrummer** [comment]
Sorry @patinthehat, I'm using v1.21.0 and there's no support to types.
