### ISSUE TITLE
rayInit is not defined

### ISSUE THREAD

**Issue by gander** [permafrost-dev/node-ray#235]
**Describe the bug**

`Uncaught ReferenceError: rayInit is not defined`

**To Reproduce**

1. Load `https://cdn.jsdelivr.net/npm/node-ray@1.21.0/dist/standalone.js`
2. Try in console `rayInit(window);`

**Expected behavior**

`ray()` declared and working:

+ `1.20.3`
+ `1.20.5`
+ `1.20.6`
+ `1.20.7`
+ `1.20.9`

**Environment (please complete the following information):**

 - OS: Linux
 - Language & Version JavaScript

**Comment by patinthehat** [comment]
@gander Thank you for reporting this issue, I will look into it.

**Comment by patinthehat** [comment]
@gander Please try using `node-ray@2.0.0`, which I released today. It should resolve this issue; please open another issue if you run into the issue again.  Thanks!
