### ISSUE TITLE
getSync2 is not a function

### ISSUE THREAD

**Issue by jskorlol** [permafrost-dev/node-ray#237]
```jsx
"node-ray": "^1.21.0",
```

index.js File
```jsx

import { ray, Ray } from 'node-ray';
ray(`test`).blue();
```

```jsx
const st = getSync2({});
                 ^
TypeError: getSync2 is not a function
```

I have installed node-ray and imported it using ES6 syntax in Node.js. However, when I call it, an error occurs.
I do not encounter any issues when using CommonJS, but the problem arises only with ES6.

**Comment by patinthehat** [comment]
@jskorlol Could you elaborate on the build process you're using?

**Comment by chokchai** [comment]
Is there any update or work around? 
Thank you.

**Comment by patinthehat** [comment]
@chokchai No updates yet (I haven't had time) but I plan to tackle this in the next few weeks when i migrate the library to vite.

**Comment by patinthehat** [comment]
@chokchai @jskorlol Please install `v2.0.0` - the new version should resolve your issue.  Thanks!
