### ISSUE TITLE
Chained ray() methods are not always followed.

### ISSUE THREAD

**Issue by TWithers** [permafrost-dev/node-ray#267]
I have a call that looks like `ray().toJson(jsonValue).color(componentColor).label(componentName)` that gets called fairly often while on a page. The problem is that the snippet of code will initiate 3 requests to the ray server instead of 1. This causes some sort of race condition which means that the label or color may not apply to the initial payload. It does seem to work about 80% of the time, but when I am issuing this call quickly back to back for different components, it will likely fail.

The solution I have implemented is to tap into the `sending_payload_callback` setting and attach a new ColorPayload and a LabelPayload to the initial payload. As far as I can tell this works, but it is a painful work around. Perhaps there could be a new method called `chain()` which would allow me to do something like `ray().chain( (ray) => ray.toJson(jsonValue).color(componentColor).label(componentName) )`.

Another issue was that the Payload objects were not exported, so I couldn't import them inside vite. I ended up copying the code from the esm module to create the Payload classes.

**Comment by patinthehat** [comment]
@TWithers Thanks for the bug report! I implemented your suggestion for `chain()` in [version 2.1.0](https://github.com/permafrost-dev/node-ray/releases/tag/v2.1.0).
