### ISSUE TITLE
Object and Array 'debugging' leads to unparsed html in ray-app

### ISSUE THREAD

**Issue by koernchen02** [permafrost-dev/node-ray#3]
**Describe the bug**

When  I log/debug – or how to call it – arrays and objects as mentioned in your docs, 
I get unparsed html in the ray app. I don't know if this is a problem with the linux ray electron app or your post payload?

**To Reproduce**

log something with node-ray:

```js
ray('a string');

ray(['several', 'arguments'], 'can', {be: {provided: 'probably an object'}});

ray().table(['one two', {a: 100, b: 200, c: 300}, [9, 8, 7]]).blue();

ray().html('<em>large text</em>').large().green();

ray().image('https://placekitten.com/200/300');
```

**Screenshots**

![2021-02-07_14-17-50](https://user-images.githubusercontent.com/312900/107147656-75864a00-694f-11eb-8297-b6471191209e.png)

**Comment by patinthehat** [comment]
Definitely a bug on this end.  I'll look into it and update this issue once I've resolved it.  Thank you!

**Comment by koernchen02** [comment]
You are my Sunday-Hero and I'd like to know if I could send you a little present via paypal or something else to show my gratitude!

**Comment by patinthehat** [comment]
Please update the package to v1.3.0, which resolves this issue.  Thank you!

That's a very kind offer.  In lieu of sending me something, please donate a small amount to [First Book](https://www.firstbook.org), a charity that helps provide books and education to underprivileged children.

**Comment by koernchen02** [comment]
version 1.3.0 seems to fix this! Still not sure if the table debug looks like it should, but the object/array debugging looks beautiful now!!! As I said, please let me know if I could send you 'something for your trouble' :)

**Comment by koernchen02** [comment]
I will do as you suggested!

**Comment by koernchen02** [comment]
I'm not able to donate from germany :( and I'm not able to write you in private on twitter (thought I could send money to your account, and you could do the actual donation)!
I would very much like to stand by my word, if it is to much trouble I can understand, but please acknowledge that I tried!
Have a nice sunday! 
Best wishes
Christian

**Comment by patinthehat** [comment]
Please feel free to donate to any charity of your choice - doesn't have to be US-based.  Thanks again, friend.
