### ISSUE TITLE
Polyfill for console

### ISSUE THREAD

**Issue by rushi** [permafrost-dev/node-ray#5]
I'd like to discuss if it would be a good idea to polyfill `console.log`, `console.info` for basic logging. So if `ray` is defined the information goes to ray, and if not, it goes straight to the console. 

This might help in cross functional teams where one dev has ray and the other doesn't. 

Any thoughts?

**Comment by patinthehat** [comment]
I'm open to the idea.  Are you saying that, for example, `ray().html('blah')`, would map to `console.log('[ray.html] blah')` or something along those lines?  Or just calls like `ray('one', 2, 3)` => `console.log('one', 2, 3)`?

Please elaborate on exactly what you're thinking.

**Comment by rushi** [comment]
I'm thinking that if someone puts `console.log` it goes to ray, if it's running. This is so if one dev is writing console.log statements it shows up in the console for them, but if I have ray, it shows up in the app for me.

**Comment by patinthehat** [comment]
How would I determine if you have Ray running or not?

**Comment by rushi** [comment]
I thought of `ray().enabled()` by looking at the docs, but I was incorrect. So the other way is to attempt a network connection (same way we send data). 

Quick test. If ray is enabled, it connects to the port
```
§ telnet localhost 23517
Trying ::1...
Connected to localhost. // <--- Success
```

If ray is disabled
```
§ telnet localhost 23517
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
Trying fe80::1...
telnet: connect to address fe80::1: Connection refused
telnet: Unable to connect to remote host
```

This should be easy with whatever module the lib uses to send requests to ray

**Comment by rushi** [comment]
> @rushi How would I determine if you have Ray running or not?
> 
> Is this sort of what you have in mind _(this is just a quick mockup)_?
> 
> ```js
> function wrapConsoleLog() {
>     window.consoleLog = console.log;
>     console.log = wrapper;
> }
> 
> function wrapper(...args) {
>     if (typeof window['ray'] !== 'undefined') {
>         return ray(...args);
>     }
>     return window.consoleLog(...args);
> }
> 
> wrapConsoleLog();
> ```

Yeah the mock up looks good, except in addition to checking ray undefined, we can also check if ray is running. 

The library can also implement `ray().running()` to return true/false if the app is running. That would be useful. The end user can do with that whatever they want, and we can use it too based on my above comment

**Comment by patinthehat** [comment]
That's not a bad idea, I think it could be very useful.  I already implemented something similar (a connection check) in the original `spatie/ray` package.  

I'm not sure this belongs in `node-ray` directly though. I feel that maybe it'd be better as a secondary package that's specific to web development and just implements `node-ray`.

What do you think?

**Comment by rushi** [comment]
>
> I'm not sure this belongs in `node-ray` directly though. I feel that maybe it'd be better as a secondary package that's specific to web development and just implements `node-ray`.
> 
Well `node-ray` serves as an interface to ray, so I do believe it belongs in the library. I'm using ray in a server & CLI app and do use plenty of console.log for debugging in there, so this is not exclusive to web development.

**Comment by patinthehat** [comment]
That's a good point.  Let me see what I can put together.

**Comment by patinthehat** [comment]
@rushi I've added a basic version of the console interceptor, but at the moment it's manually enabled:

```js
async function main() {
    await ray().client().updateRayAvailabilty();

    console.log('test 1');
    ray().interceptor().enable();
    console.log('test 2');
}

main();
```
When Ray is not running:
![image](https://user-images.githubusercontent.com/5508707/107583013-51816d80-6bc8-11eb-82ca-b1dd644781f6.png)

When Ray is running:
![image](https://user-images.githubusercontent.com/5508707/107583060-63fba700-6bc8-11eb-8c55-a7942717c287.png)
![image](https://user-images.githubusercontent.com/5508707/107583083-707fff80-6bc8-11eb-8d7f-c4b5b66cd80c.png)

Is this more or less what you had in mind? And if you don't care about `console.log()` writing to the console even if Ray is running, then we can probably clean that up a bit.

**Comment by rushi** [comment]
Yeah this is exactly what I had in mind. I'll give this a spin in my app and see if I have any feedback

**Comment by rushi** [comment]
Ran into an error while testing it:
```
error - ./node_modules/node-ray/dist/index.cjs.js:5:0
Module not found: Can't resolve 'fs'
```

**Comment by rushi** [comment]
Never mind, my mistake. I should have imported `node-ray/web` instead of `node-ray`

**Comment by mikeerickson** [comment]
So, this is a wonderful idea.  What are the reason(s) behind making this enabling a manual process?

**Comment by patinthehat** [comment]
@mikeerickson What do you mean?
