### ISSUE TITLE
[FEATURE] No declaration file when using in a TypeScript envoronment

### ISSUE THREAD

**Issue by koernchen02** [permafrost-dev/node-ray#6]
**Describe the bug**

Whe importing node-ray/web in a typescript application, I get the following error:

```
TS7016: Could not find a declaration file for module 'node-ray/web'.
 '../node_modules/node-ray/web.js' implicitly has an 'any' type.   
Try `npm i --save-dev @types/node-ray` if it exists or add a new declaration (.d.ts) file containing `declare module 'node-ray/web';`
```
Would it be possible to generate a type definition with rollup?

**Comment by patinthehat** [comment]
Absolutely.  It's something I'll be adding in an upcoming release.

**Comment by patinthehat** [comment]
@koernchen02 I've added a typescript declaration file as of v1.5.2.  If you update your installation you should now have typescript completion.  Please let me know if you're still having issues after updating.

Thanks for the suggestion!

**Comment by koernchen02** [comment]
Works fantastic! :pray:
