### ISSUE TITLE
ray call fails after clearing screen (using clearAll, newScreen, or clearScreen)

### ISSUE THREAD

**Issue by mikeerickson** [permafrost-dev/node-ray#7]
The following will clear the screen, however, the subsequent call to ray has no affect

```js
ray().clearAll() // or ray().newScreen() or ray().clearScreen()
ray('test')
```

1. Follow the simple example above

**Expected behavior**

A clear screen should be followed by normal output

This is how the Ray console appears after above example

![image](https://user-images.githubusercontent.com/183153/108002140-79dfe200-6fa3-11eb-8c44-6e4e2de24020.png)

**Environment (please complete the following information):**

 - OS: macOS 10.15.7
 - NodeJS Version 14.5.0

**Comment by patinthehat** [comment]
Thanks, I'm looking into this now.

**Comment by patinthehat** [comment]
@mikeerickson version 1.9.1+ should resolve this issue.  Please reopen if you're still running into issues.

Thank you!
