### ISSUE TITLE
Calls to ray are not sequential

### ISSUE THREAD

**Issue by mikeerickson** [permafrost-dev/node-ray#8]
It seems calls to `ray()` are not actually sequential (see related issue https://github.com/permafrost-dev/node-ray/issues/7)

```js
    ray('string 1')
    ray('string 2')
    ray('string 3')
    ray('string 4')
    ray('string 5')
```

1. Use the above example

**Expected behavior**

I am expecting to see the calls in sequential order, however, they are more like `async` calls

**Screenshots**
![image](https://user-images.githubusercontent.com/183153/108002449-887ac900-6fa4-11eb-84ef-efffef099048.png)

**Environment (please complete the following information):**

 - OS: macOS 10.15.7
 - NodeJS Version 10.15.7

Note: This could be the same issue as reported regarding `clearAll()` issue

https://github.com/permafrost-dev/node-ray/issues/7

**Comment by mikeerickson** [comment]
Closed by mistake, this issues still exists

**Comment by patinthehat** [comment]
Thanks, I'm looking into this now.

**Comment by patinthehat** [comment]
@mikeerickson version 1.9.1+ should resolve this issue.  Please reopen if you're still running into issues.

Thank you!
