### ISSUE TITLE
Information missing

### ISSUE THREAD

**Issue by eduwass** [permafrost-dev/node-ray#84]
Created from initial discussion here:
https://github.com/permafrost-dev/node-ray/discussions/79

**Describe the bug**

I am able to send some messages through to Ray, but a lot of information seems to be missing.

- Ray doesn't seem to know path, see: `unknown-file.js:1`
-  `caller()` and `trace()` functions do not output anything

**To Reproduce**

1. Try to add Ray to a Next.js project
2. Add some Ray debug messages

**Expected behavior**

Ray should show path and caller() , trace() functions should work.

**Screenshots**

![CleanShot 2022-05-23 at 02 50 47](https://user-images.githubusercontent.com/1070495/169724325-32eb8d8f-7b73-48e8-abb8-27578ec72de6.png)

**Environment (please complete the following information):**

 - OS: Mac OS 12.4
 - NodeJS Version 14.17.1
 - Language & Version: see package.json below

**Additional context**

I am using "node-ray/web" because if I try to import "node-ray" I'll get the following error

```
error - ./node_modules/node-ray/node_modules/locate-path/index.js:3:0
Module not found: Can't resolve 'fs'

Import trace for requested module:
./node_modules/node-ray/node_modules/find-up/index.js
./node_modules/node-ray/dist/index.esm.mjs
./pages/index.tsx
```

The project is based on create-next-app here's the package.json contents:

```
{
  "name": "project",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@emotion/react": "^11.9.0",
    "@emotion/styled": "^11.8.1",
    "@hookform/resolvers": "^2.8.10",
    "@mui/material": "^5.7.0",
    "@mui/x-data-grid": "^5.10.0",
    "axios": "^0.27.2",
    "cookies-next": "^2.0.4",
    "next": "12.1.6",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-hook-form": "^7.31.1",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@types/node": "17.0.31",
    "@types/react": "18.0.9",
    "@types/react-dom": "18.0.3",
    "eslint": "8.15.0",
    "eslint-config-next": "12.1.6",
    "node-ray": "^1.18.0",
    "typescript": "4.6.4"
  }
}
```

**Comment by patinthehat** [comment]
@eduwass Thank you for reporting this issue, I'll look into it.

**Comment by patinthehat** [comment]
@eduwass I see you're using `node-ray/web` - this package does not have access to the filesystem, therefore it cannot determine what file is it being sent from. I believe the `caller()` and `trace()` functions are NodeJS-specific as well.

Since you're using Next.js, I suggest you use the official React integration for Ray: [`react-ray`](https://github.com/permafrost-dev/react-ray).
